language: node_js
sudo: required
node_js:
- node
before_deploy: 
- curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
- chmod -R u+x ./Bluemix_CLI/bin
- chmod +x ./deploy.sh
deploy: 
  provider: script
  script: ./deploy.sh
  on:
    repo: ibm-watson-data-lab/soslackbot
    branch: master
  skip_cleanup: true
